<?php
/**
 * @var \Addi\Payment\Block\Adminhtml\PaymentInfo $block
 */
$order = $block->getOrder();
$payment = $block->getPayment();
$addiOrderId = $payment->getAdditionalInformation('addi_order_id');
$addiApplicationId = $payment->getAdditionalInformation('addi_application_id');
$addiApprovedAmount = $payment->getAdditionalInformation('addi_approved_amount');
$addiCurrency = $payment->getAdditionalInformation('addi_currency');
$addiStatus = $payment->getAdditionalInformation('addi_status');
?>
<br>
<?php if($addiOrderId): ?>
<strong>
    <?php echo $block->escapeHtml(__('Addi Order Id')) ?>
</strong>: <?php echo $block->escapeHtml($addiOrderId) ?><br>
<strong>
    <?php echo $block->escapeHtml(__('Addi Application Id')) ?>
</strong>: <?php echo $block->escapeHtml($addiApplicationId) ?><br>
<strong>
    <?php echo $block->escapeHtml(__('Addi Approved Amount')) ?>
</strong>: <?php echo $block->escapeHtml($addiApprovedAmount) ?><br>
<strong>
    <?php echo $block->escapeHtml(__('Addi Currency')) ?>
</strong>: <?php echo $block->escapeHtml($addiCurrency) ?><br>
<strong>
    <?php echo $block->escapeHtml(__('Addi Status')) ?>
</strong>: <?php echo $block->escapeHtml($addiStatus) ?>
<?php endif; ?>
