<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Addi\Payment\Block\Adminhtml\PaymentInfo $block
 */
$order = $block->getOrder();
$payment = $block->getPayment();
$addiOrderId = $payment->getAdditionalInformation('addi_order_id');
$addiApplicationId = $payment->getAdditionalInformation('addi_application_id');
$addiApprovedAmount = $payment->getAdditionalInformation('addi_approved_amount');
$addiCurrency = $payment->getAdditionalInformation('addi_currency');
$addiStatus = $payment->getAdditionalInformation('addi_status');
?>
<br>
<?php if($addiOrderId): ?>
<strong><?= $block->escapeHtml(__('Addi Order Id')) ?></strong>: <?= $block->escapeHtml($addiOrderId) ?><br>
<strong><?= $block->escapeHtml(__('Addi Application Id')) ?></strong>: <?= $block->escapeHtml($addiApplicationId) ?><br>
<strong><?= $block->escapeHtml(__('Addi Approved Amount')) ?></strong>: <?= $block->escapeHtml($addiApprovedAmount) ?><br>
<strong><?= $block->escapeHtml(__('Addi Currency')) ?></strong>: <?= $block->escapeHtml($addiCurrency) ?><br>
<strong><?= $block->escapeHtml(__('Addi Status')) ?></strong>: <?= $block->escapeHtml($addiStatus) ?>
<?php endif; ?>
