<div class="container-addi-principal">
    <div class="addi-container-flex">
        <div class="simple">Tú decides a cuántas cuotas comprar</div>

        <div class="description-addi">
            <div class="description"><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/icons01.svg'); ?>" alt=""> Compra a cuotas a <b>partir de 0% de interés*</b></div>
            <div class="description"><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/icons02.svg'); ?>" alt=""> Solo necesitas <b>tu cédula y WhatsApp</b> para comprar</div>
            <div class="description-subtitle">*La opción de 0% está sujeta a criterios de elegibilidad y <a target="_blank" href="https://co.addi.com/terminos-y-condiciones">T&C</a> de Addi.</div>
            <div class="description">Haz clic en <b>"Realizar pedido"</b> para continuar.</div>
        </div>
    </div>
</div>

