<div class="container-addi-principal">
    <div class="addi-container-flex">
        <div class="simple">Tú decides a cuántas cuotas comprar</div>

        <div class="description-addi">
            <div class="description"><p><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/icons01.svg'); ?>" alt="">Escoge entre <b>1 y 3 cuotas </b>con 0% de interés.</p></div>
            <div class="description"><p><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/icons04.svg'); ?>" alt="">Elige entre <b>4 y 6 cuotas </b>con intereses.</p></div>
            <div class="description"><p><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/icons02.svg'); ?>" alt="">Solo necesitas <b>tu cédula y WhatsApp</b> para comprar</p></div>
            <div class="description-subtitle">*La opción de 0% está sujeta a criterios de elegibilidad y <a target="_blank" href="https://co.addi.com/terminos-y-condiciones">T&C</a> de Addi.</div>
            <div class="description">Haz clic en <b>"Realizar pedido"</b> para continuar.</div>
        </div>
    </div>
</div>

