<div class="container-addi-principal">
    <div class="addi-container">
        <div class="header-addi">Después de hacer clic en "Place order" será redirigido a Addi.</div>

        <div class="logo-container">
            <div class="logo"><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/addi-logo.png'); ?>" alt="">
            </div>
            <div class="payment-latter">
                <b>Compra ahora paga después</b>
            </div>
        </div>

        <div class="simple">Es fácil, rápido y seguro</div>

        <div class="description-addi">
            <div class="description">Sin tarjetas de crédito y en minutos</div>
            <div class="description">Solo necesitas tu cédula y WhatsApp para aplicar</div>
            <div class="description">Proceso 100% online y sin papeleo</div>
        </div>
    </div>
</div>
