<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    '\Addi\Addi'            => __DIR__ . '/src/Addi.php',
    '\Addi\Addi\Amount'     => __DIR__ . '/src/Data/Amount.php',
    '\Addi\Addi\Item'       => __DIR__ . '/src/Data/Item.php',
    '\Addi\Addi\Shipping'   => __DIR__ . '/src/Data/Shipping.php',
    '\Addi\Addi\Billing'    => __DIR__ . '/src/Data/Billing.php',
    '\Addi\Addi\PickUpAddress'    => __DIR__ . '/src/Data/PickUpAddress.php',
    '\Addi\Addi\Client'    => __DIR__ . '/src/Data/Billing.php',
);
