<div class="addi-container">
    <div class="header">Após clicar em “placer order”, você será redirecionado para Addi.</div>

    <div class="logo-container">
        <div class="logo"><img src="<?php echo $this->getViewFileUrl('Addi_Payment::images/addi-logo.png'); ?>" alt="">
        </div>
        <div class="payment-latter">
            <b>Pague com PIX e adiante sua vida!</b>
        </div>
    </div>

    <div class="description-addi">
        <div class="description">
            Com <b>Addi</b> você pode escolher a melhor opção para pagar <b>com pix:</b><br>
            <ul>
                <li>PIX à vista!</li>
                <li>1 + 3x no PIX, sem juros!*</li>
            </ul>
            Você só precisa do Pix e seu WhatsApp
        </div>
    </div>

    <div class="cpf">
        *O pagamento precisa ter o mesmo CPF da compra
    </div>
</div>
